const GET_ALL_PRODUCT_OF_SHOP = 'GET_ALL_PRODUCT';
const SORT_PRODUCT_BY_PRICE = 'SORT_PRODUCT_BY_PRICE'
const SORT_PRODUCT_BY_NEWER = 'SORT_PRODUCT_BY_NEWER'
const SORT_PRODUCT_BY_SELLER = 'SORT_PRODUCT_BY_SELLER'

export {
    GET_ALL_PRODUCT_OF_SHOP,
    SORT_PRODUCT_BY_PRICE,
    SORT_PRODUCT_BY_NEWER,
    SORT_PRODUCT_BY_SELLER
};
