const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
const DELETE_FROM_WISHLIST = 'DELETE_FROM_WISHLIST'
const UPDATE_QUANTITY = 'UPDATE_QUANTITY'

export {ADD_TO_WISHLIST, DELETE_FROM_WISHLIST, UPDATE_QUANTITY}