const NAVIGATE_ONBOARDING: string = 'Onboarding'
const NAVIGATE_LOGIN: string = 'Login'
const NAVIGATE_CART: string = 'CartNavigator'
const NAVIGATE_PRODUCT_DETAIL: string = 'ProductDetail'
const NAVIGATE_SETTINGS: string = 'Settings'
const NAVIGATE_SOCIAL_NETWORK: string = 'SocialNetwork'
const NAVIGATE_CHANGE_INFO: string = 'ChangeInfo'
const NAVIGATE_FILTER: string = 'Filter'
const NAVIGATE_CART_ADDRESS: string = 'CartAddress'
const NAVIGATE_ADD_NEW_ADDRESS: string = 'AddNewAddress'
const NAVIGATE_RATING: string = 'Rating'
const NAVIGATE_ADDRESS: string = 'Address'
const NAVIGATE_UPDATE_INFO: string = 'UpdateInfo'
const NAVIGATE_HOME: string = 'TabBar'
const NAVIGATE_SHOP_DETAIL = 'ShopDetail'
const NAVIGATE_REGISTER_SCREEN = 'Register'
const NAVIGATE_FORGOT_PASSWORD = 'ForgotPassword'
const NAVIGATE_LOGINSMS_SCREEN = 'LoginSMS'
const NAVIGATE_SEARCH_SCREEN = 'Search'
const NAVIGATE_SEARCH_DETAIL_SCREEN = ''

export {
    NAVIGATE_ONBOARDING,
    NAVIGATE_LOGIN,
    NAVIGATE_CART,
    NAVIGATE_PRODUCT_DETAIL,
    NAVIGATE_SETTINGS,
    NAVIGATE_SOCIAL_NETWORK,
    NAVIGATE_CHANGE_INFO,
    NAVIGATE_FILTER,
    NAVIGATE_CART_ADDRESS,
    NAVIGATE_ADD_NEW_ADDRESS,
    NAVIGATE_RATING,
    NAVIGATE_ADDRESS,
    NAVIGATE_UPDATE_INFO,
    NAVIGATE_HOME,
    NAVIGATE_SHOP_DETAIL,
    NAVIGATE_REGISTER_SCREEN,
    NAVIGATE_FORGOT_PASSWORD,
    NAVIGATE_LOGINSMS_SCREEN,
    NAVIGATE_SEARCH_SCREEN,
    NAVIGATE_SEARCH_DETAIL_SCREEN
}